name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install luacheck
        run: |
          apt-get update 1>/dev/null || exit 1
          apt-get install -yq lua-check 1>/dev/null || exit 1

      - run: echo "🎉 The job was ${{ gitea.actor }} automatically ${{ gitea.repository }} triggered by a ${{ gitea.files }} event."
      - run: pwd
      - run: ls -lrt
      - name: Check version
        run: luacheck ${{ inputs.args }} -- ${{ inputs.files }}